[package]
name = "wx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wx-base = { path = "../wx-base" }

[build-dependencies]
cc = "1.0.72"
