[workspace]

default-members = [
    "wx-base",
    "wx-core",
]

members = [
    "samples/hello",
    "samples/minimal",
    "samples/widgets",
    "samples/wrapsizer",
    "wx-base",
    "wx-core",
    "wxrust-config",
]