wxml_files = [
    #'wxml/classwx_activity_indicator.xml',
    'wxml/classwx_any_button.xml',
    'wxml/classwx_art_provider.xml',
    'wxml/classwx_bitmap.xml',
    'wxml/classwx_book_ctrl_base.xml',
    'wxml/classwx_book_ctrl_event.xml',
    'wxml/classwx_box_sizer.xml',
    'wxml/classwx_button.xml',
    'wxml/classwx_check_box.xml',
    'wxml/classwx_colour.xml',
    'wxml/classwx_command_event.xml',
    'wxml/classwx_control.xml',
    'wxml/classwx_event.xml',
    'wxml/classwx_evt_handler.xml',
    'wxml/classwx_frame.xml',
    'wxml/classwx_g_d_i_object.xml',
    'wxml/classwx_list_box.xml',
    'wxml/classwx_menu.xml',
    'wxml/classwx_menu_bar.xml',
    'wxml/classwx_menu_item.xml',
    'wxml/classwx_non_owned_window.xml',
    'wxml/classwx_notebook.xml',
    'wxml/classwx_notify_event.xml',
    'wxml/classwx_object.xml',
    'wxml/classwx_panel.xml',
    'wxml/classwx_point.xml',
    'wxml/classwx_radio_box.xml',
    'wxml/classwx_rect.xml',
    'wxml/classwx_size.xml',
    'wxml/classwx_sizer.xml',
    'wxml/classwx_sizer_flags.xml',
    'wxml/classwx_static_bitmap.xml',
    'wxml/classwx_static_box.xml',
    'wxml/classwx_static_box_sizer.xml',
    'wxml/classwx_static_text.xml',
    'wxml/classwx_text_attr.xml',
    'wxml/classwx_text_ctrl.xml',
    'wxml/classwx_text_entry.xml',
    'wxml/classwx_tool_bar.xml',
    'wxml/classwx_top_level_window.xml',
    'wxml/classwx_validator.xml',
    'wxml/classwx_window.xml',
    'wxml/classwx_wrap_sizer.xml',
]

[conditions]

[conditions.windows]
cxx = "#ifdef __WXMSW__"

[conditions.not_windows]
cxx = "#ifndef __WXMSW__"

[conditions.mac]
cxx = "#ifdef __WXOSX__"

[conditions.not_gtk]
cxx = "#ifndef __WXGTK__"

[conditions.wx31]
cxx = "#if wxCHECK_VERSION(3, 1, 0)"

[types]
[types.wxAnyButton]
library = 'core'
[types.wxArtProvider]
blocklist = [
    'Insert',
]
[types.wxBitmap]
blocklist = [
    # doesn't support returning wxList
    'GetHandlers',
]
wx31 = [
    'wxBitmap8',
]
not_windows = [
    # FIXME: FindHandler on MSW requires dynamic_cast in C++ generated code.
    'FindHandler',
]
[types.wxBookCtrlBase]
blocklist = [
    'wxBookCtrlBase',
    'wxBookCtrlBase1',
]
[types.wxButton]
wx31 = [
    'GetDefaultSize',
]
[types.wxColour]
blocklist = [
    'operator=',
    'operator==',
    'operator!=',
    'ChangeLightness',
]
wx31 = [
    'GetLuminance',
    'IsSolid',
]
[types.wxControl]
wx31 = [
    'GetSizeFromText',
]
[types.wxEvent]
returns_owned = [
    'Clone',
]
[types.wxEvtHandler]
blocklist = [
    'Bind1',
    'CallAfter1',
    'GetClientData',
    'SetClientData',
    'Unbind1',
]
[types.wxFrame]
windows = [
    'MSWGetTaskBarButton',
]
[types.wxGDIObject]
blocklist = [
    # abstract class
    'wxGDIObject',
]
[types.wxListBox]
blocklist = [
    'MSWSetTabStops',
]
wx31 = [
    'GetCountPerPage',
    'GetTopItem',
]
[types.wxMenu]
blocklist = [
    # returns refs
    'GetMenuItems',
    'GetMenuItems1',
]
[types.wxMenuBar]
blocklist = [
    'GetLabelTop',
    'SetLabelTop',
]
mac = [
    'MacGetCommonMenuBar',
    'MacSetCommonMenuBar',
    'OSXGetAppleMenu',
]
[types.wxMenuItem]
blocklist = [
    'GetLabelFromText',
    # Probably documentation mismatch
    'GetBitmap',
    'SetBitmap',
    # Deprecated, maybe removed
    'GetLabel',
    'GetName',
    'GetText',
    'SetText',
]
windows = [
    'GetBackgroundColour',
    'GetDisabledBitmap',
    'GetFont',
    'GetMarginWidth',
    'GetTextColour',
    'SetBackgroundColour',
    'SetBitmaps',
    'SetDisabledBitmap',
    'SetFont',
    'SetMarginWidth',
    'SetTextColour',
]
[types.wxNonOwnedWindow]
library = 'core'
[types.wxNotebook]
blocklist = [
    'Create',
    'OnSelChange',
]
[types.wxObject]
blocklist = [
    'operator new',
    'operator delete',
]
[types.wxPoint]
blocklist = [
    'operator+',
    'operator+1',
    'operator+2',
    'operator-',
    'operator-1',
    'operator-2',
    'operator/',
    'operator*',
    'operator*1',
    'operator=',
    'operator==',
    'operator!=',
    'operator+=',
    'operator+=1',
    'operator-=',
    'operator-=1',
    'operator/=',
    'operator*=',
]
[types.wxRect]
blocklist = [
    'operator==',
    'operator=',
    'operator*=',
    'operator*',
    'operator+=',
    'operator+',
    'operator!=',
    # returns refs
    'Deflate',
    'Deflate1',
    'Deflate2',
    'Inflate',
    'Inflate1',
    'Inflate2',
    'Intersect',
    'Union1',
]
[types.wxSize]
blocklist = [
    'operator+',
    'operator-',
    'operator/',
    'operator*',
    'operator*1',
    'operator=',
    'operator==',
    'operator!=',
    'operator+=',
    'operator-=',
    'operator/=',
    'operator*=',
    # Didn't support
    'Scale',
]
[types.wxSizer]
blocklist = [
    # virtual
    'wxSizer',
    # returns refs
    'GetChildren',
    'GetChildren1',
    # deprecated, use Remove() without args
    'Remove',
    # deprecated, use FitInside()
    'SetVirtualSizeHints',
]
wx31 = [
    'RepositionChildren',
]
[types.wxSizerFlags]
wx31 = [
    'CenterHorizontal',
    'CenterVertical',
    'CentreHorizontal',
    'CentreVertical',
]
[types.wxStaticBox]
blocklist = [
    'wxStaticBox2',
    'Create1',
]
[types.wxTextAttr]
blocklist = [
    'operator=',
    # TODO: wxArrayInt is not supported
    'GetTabs',
]
wx31 = [
    'GetUnderlineColour',
]
[types.wxTextCtrl]
blocklist = [
    'operator<<',
    'operator<<1',
    'operator<<2',
    'operator<<4',
]
[types.wxToolBar]
blocklist = [
    # const getter
    'GetToolByPos',
]
[types.wxTopLevelWindow]
windows = [
    'MSWGetSystemMenu',
]
blocklist = [
    # wxUniversal specific
    'IsUsingNativeDecorations',
    'UseNativeDecorations',
    'UseNativeDecorationsByDefault',

    # Didn't support (Uses inner class)
    'GetIcons',
    'SaveGeometry',
    'RestoreToGeometry',
]
wx31 = [
    'EnableFullScreenView',
    'EnableMaximizeButton',
    'EnableMinimizeButton',
]
[types.wxValidator]
returns_owned = [
    'Clone',
]
[types.wxWindow]
blocklist = [
    # TODO: dont return reference/temp value from self
    'GetChildren',
    'GetCursor',
    'GetUpdateRegion',
]
not_gtk = [
    'RegisterHotKey',
    'UnregisterHotKey',
]
wx31 = [
    'DisableFocusFromKeyboard',
    'EnableTouchEvents',
    'EnableVisibleFocus',
    'FromDIP',
    'FromDIP1',
    'FromDIP2',
    'FromDIP3',
    'FromDIP4',
    'FromDIP5',
    'GetDPI',
    'GetDPIScaleFactor',
    'InheritsForegroundColour',
    'ToDIP',
    'ToDIP1',
    'ToDIP2',
    'ToDIP3',
    'ToDIP4',
    'ToDIP5',
    'UseBackgroundColour',
    'UseForegroundColour',
]
