wxml_files = [
    'wxml/classwx_object.xml',
    'wxml/classwx_art_provider.xml',
    'wxml/classwx_bitmap.xml',
    'wxml/classwx_box_sizer.xml',
    'wxml/classwx_command_event.xml',
    'wxml/classwx_event.xml',
    'wxml/classwx_evt_handler.xml',
    'wxml/classwx_g_d_i_object.xml',
    'wxml/classwx_window.xml',
    'wxml/classwx_control.xml',
    'wxml/classwx_any_button.xml',
    'wxml/classwx_button.xml',
    'wxml/classwx_menu.xml',
    'wxml/classwx_menu_bar.xml',
    'wxml/classwx_non_owned_window.xml',
    'wxml/classwx_tool_bar.xml',
    'wxml/classwx_top_level_window.xml',
    'wxml/classwx_frame.xml',
    'wxml/classwx_panel.xml',
    'wxml/classwx_point.xml',
    'wxml/classwx_rect.xml',
    'wxml/classwx_size.xml',
    'wxml/classwx_sizer.xml',
    'wxml/classwx_sizer_flags.xml',
    'wxml/classwx_static_box_sizer.xml',
    'wxml/classwx_validator.xml',
    'wxml/classwx_static_bitmap.xml',
]

[conditions]

[conditions.windows]
cxx = "#ifdef __WXMSW__"

[conditions.mac]
cxx = "#ifdef __WXOSX__"

[conditions.not_gtk]
cxx = "#ifndef __WXGTK__"

[conditions.wx31]
cxx = "#if wxCHECK_VERSION(3, 1, 0)"

[types]
[types.wxBitmap]
blocklist = [
    'wxBitmap8',
    # doesn't support returning wxList
    'GetHandlers',
]
[types.wxGDIObject]
blocklist = [
    'wxGDIObject',
    'CloneGDIRefData',
    'CreateGDIRefData',
]
[types.wxObject]
blocklist = [
    'operator delete',
]
[types.wxEvent]
returns_owned = [
    'Clone',
]
[types.wxEvtHandler]
blocklist = [
    'Bind1',
    'CallAfter1',
    'GetClientData',
    'SetClientData',
    'Unbind1',
]
[types.wxWindow]
blocklist = [
    # TODO: dont return reference/temp value from self
    'GetChildren',
    'GetChildren1',
    'GetCursor',
    'GetUpdateRegion',
]
not_gtk = [
    'RegisterHotKey',
    'UnregisterHotKey',
]
wx31 = [
    'DisableFocusFromKeyboard',
    'EnableTouchEvents',
    'EnableVisibleFocus',
    'FromDIP',
    'FromDIP1',
    'FromDIP2',
    'FromDIP3',
    'FromDIP4',
    'FromDIP5',
    'GetDPI',
    'GetDPIScaleFactor',
    'InheritsForegroundColour',
    'ToDIP',
    'ToDIP1',
    'ToDIP2',
    'ToDIP3',
    'ToDIP4',
    'ToDIP5',
    'UseBackgroundColour',
    'UseForegroundColour',
]
[types.wxControl]
wx31 = [
    'GetSizeFromText',
]
[types.wxAnyButton]
library = 'core'
[types.wxButton]
wx31 = [
    'GetDefaultSize',
]
[types.wxMenu]
blocklist = [
    # returns refs
    'GetMenuItems',
    'GetMenuItems1',
]
[types.wxMenuBar]
mac = [
    'MacGetCommonMenuBar',
    'MacSetCommonMenuBar',
    'OSXGetAppleMenu',
]
[types.wxNonOwnedWindow]
library = 'core'
[types.wxToolBar]
blocklist = [
    # const getter
    'GetToolByPos',
]
[types.wxTopLevelWindow]
windows = [
    'MSWGetSystemMenu',
]
blocklist = [
    # wxUniversal specific
    'IsUsingNativeDecorations',
    'UseNativeDecorations',
    'UseNativeDecorationsByDefault',

    # Didn't support (Uses inner class)
    'GetIcons',
    'SaveGeometry',
    'RestoreToGeometry',
]
wx31 = [
    'EnableFullScreenView',
    'EnableMaximizeButton',
    'EnableMinimizeButton',
]
[types.wxFrame]
windows = [
    'MSWGetTaskBarButton',
]
[types.wxPoint]
blocklist = [
    'operator+',
    'operator+1',
    'operator+2',
    'operator-',
    'operator-1',
    'operator-2',
    'operator/',
    'operator*',
    'operator*1',
    'operator=',
    'operator==',
    'operator!=',
    'operator+=',
    'operator+=1',
    'operator-=',
    'operator-=1',
    'operator/=',
    'operator*=',
]
[types.wxRect]
blocklist = [
    'operator==',
    'operator=',
    'operator*=',
    'operator*',
    'operator+=',
    'operator+',
    'operator!=',
    # returns refs
    'Deflate',
    'Deflate1',
    'Deflate2',
    'Inflate',
    'Inflate1',
    'Inflate2',
    'Intersect',
    'Union1',
]
[types.wxSize]
blocklist = [
    'operator+',
    'operator-',
    'operator/',
    'operator*',
    'operator*1',
    'operator=',
    'operator==',
    'operator!=',
    'operator+=',
    'operator-=',
    'operator/=',
    'operator*=',
    # Didn't support
    'Scale',
]
[types.wxSizer]
blocklist = [
    # virtual
    'wxSizer',
    # maybe binding bug, return type didn't generated
    'GetChildren',
    # deprecated
    'GetChildren1',
    # deprecated, use Remove() without args
    'Remove',
    # deprecated, use FitInside()
    'SetVirtualSizeHints',
]
wx31 = [
    'RepositionChildren',
]
[types.wxSizerFlags]
wx31 = [
    'CenterHorizontal',
    'CenterVertical',
    'CentreHorizontal',
    'CentreVertical',
]
[types.wxValidator]
returns_owned = [
    'Clone',
]
