wxml_files = [
    'wxml/classwx_object.xml',
    'wxml/classwx_evt_handler.xml',
    'wxml/classwx_window.xml',
    'wxml/classwx_control.xml',
    'wxml/classwx_any_button.xml',
    'wxml/classwx_button.xml',
    'wxml/classwx_non_owned_window.xml',
    'wxml/classwx_top_level_window.xml',
    'wxml/classwx_frame.xml',
    'wxml/classwx_point.xml',
    'wxml/classwx_rect.xml',
    'wxml/classwx_size.xml',
    'wxml/classwx_validator.xml',
]

types = [
    'wxString = crate::ffi::wxString',
    'wxWindowList',
    # 'wxRect',
    'wxSizer',
    'wxFont',
    'wxRegion',
    'wxColour',
    'wxPalette',
    'wxKeyEvent',
    'wxEvent',
    'wxToolTip',
    'wxMenu',
    'wxAcceleratorTable',
    # 'wxAccessible',
    'wxDropTarget',
    'wxLayoutConstraints',
    'wxCaret',
    'wxCursor',
    'wxUpdateUIEvent',
    'wxIdleEvent',
    'wxBitmap',
    'wxCommandEvent',
    'wxClientData',
    'wxEventFilter',
    'wxClassInfo',
    'wxObjectRefData',
    # 'wxTaskBarButton',
    'wxMenuBar',
    'wxToolBar',
    'wxStatusBar',
    'wxIconBundle',
    'wxIcon',
    # 'GeometrySerializer',
    'wxGraphicsPath',
    'wxRealPoint',
    'wxDC',
]

[blocklist]
wxObject = [
    'operator delete',
]
wxEvtHandler = [
    'Bind1',
    'CallAfter1',
    'GetClientData',
    'SetClientData',
    'Unbind1',
]
wxWindow = [
    # TODO: treat long correctly
    'Create',
    # enum vs i32
    'GetHelpTextAtPoint',
    # wxWindowBase's methods
    'AddChild',
    'FindWindow',
    'FromDIP',
    'GetExtraStyle',
    'GetWindowStyle',
    'GetWindowStyleFlag',
    'IsDescendant',
    'IsExposed1',
    'IsExposed3',
    'RemoveChild',
    'Reparent',
    'SetExtraStyle',
    'SetSize1',
    'SetWindowStyle',
    'SetWindowStyleFlag',
    'ToDIP2',
    'UpdateWindowUI',

    # TODO: dont return reference/temp value from self
    'GetChildren',
    'GetChildren1',
    'GetCursor',
    'GetUpdateRegion',
]
wxControl = [
    # TODO: treat long correctly
    'Create',
    # enum vs i32
    'Ellipsize',
]
wxButton = [
    # TODO: treat long correctly
    'Create',
]
wxTopLevelWindow = [
    # TODO: treat long correctly
    'Create',
    # wxTopLevelWindowMac's methods (on Mac)
    'ShowFullScreen',
    # Other platform specific
    'IsUsingNativeDecorations',
    'MSWGetSystemMenu',
    'UseNativeDecorations',
    'UseNativeDecorationsByDefault',
    # Didn't support
    'GetIcons',
    'SaveGeometry',
    'RestoreToGeometry',
]
wxFrame = [
    # TODO: treat long correctly
    'Create',
    'CreateToolBar',
    'OnCreateStatusBar',
    # Other platform specific
    'MSWGetTaskBarButton',
    # wxFrameBase's methods
    'CreateStatusBar',
    'OnCreateToolBar',
]
wxPoint = [
    'operator+',
    'operator+1',
    'operator+2',
    'operator-',
    'operator-1',
    'operator-2',
    'operator/',
    'operator*',
    'operator*1',
    'operator=',
    'operator==',
    'operator!=',
    'operator+=',
    'operator+=1',
    'operator-=',
    'operator-=1',
    'operator/=',
    'operator*=',
]
wxRect = [
    'operator==',
    'operator=',
    'operator*=',
    'operator*',
    'operator+=',
    'operator+',
    'operator!=',
    # returns refs
    'Deflate',
    'Deflate1',
    'Deflate2',
    'Inflate',
    'Inflate1',
    'Inflate2',
    'Intersect',
    'Union1',
]
wxSize = [
    'operator+',
    'operator-',
    'operator/',
    'operator*',
    'operator*1',
    'operator=',
    'operator==',
    'operator!=',
    'operator+=',
    'operator-=',
    'operator/=',
    'operator*=',
    # Didn't support
    'Scale',
]