name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Prerequisites
      run: sudo apt install libwxgtk3.0-gtk3-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-mac:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Prerequisites
      run: brew install wxwidgets
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
