[package]
name = "wx-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wx-bin = { git = "https://github.com/ancwrd1/wx-universal-apple-darwin", package = "wx-universal-apple-darwin" }

[build-dependencies]
cc = "1.0.72"
wxrust-config = { path = "../wxrust-config" }
